#!/usr/bin/env bash

git add .

branch_name=$(git branch --show-current)
printf $branch_name

# -Q --no-build-output is broken
# nh os switch --hostname $branch_name --diff auto --impure
sudo nixos-rebuild switch --flake ./hosts/$branch_name#$branc_name

notify-send "NixOS finished rebuilding!"

if [[ $branch_name = "laptop" ]]; then
    currentDate=$(date +"LAP: %Y-%m-%d %H:%M:%S")
else
    currentDate=$(date +"WRK: %Y-%m-%d %H:%M:%S")
fi

sudo chown -R udontur:777 ./.git
git add .
git commit -m "$currentDate" &> git-commit.log

read -p "Back it up? " user_input

printf "\033[A\033[K\033[A\033[K"

if [[ $user_input =~ ^[Yy]$ ]]; then
    git push origin HEAD &> git-sync.log || (git push origin main && exit 1)
    if [ $? -ne 0 ]; then
        printf "\033[A\033[KError: Failed to back up :c\n"
        exit 1
    else
        printf "\033[A\033[KEnjoy your system! :D\n"
    fi
else
    printf "NOT backed up :c\n"
fi
