#!/usr/bin/env bash
# Load in the functions and animations
source assets/bla/bla.sh
trap BLA::stop_loading_animation SIGINT

sudo git add .

BLA::start_loading_animation "${BLA_passing_dots[@]}"
    sudo nixos-rebuild switch --flake ~/nixos --impure &> nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)
BLA::stop_loading_animation

if [ $? -eq 1 ]; then
    echo "NixOS Failed to Rebuild."
    echo "Please check nixos-switch.log and the error message"
    exit 1
else
    echo "NixOS Rebuilt Successfully!" 
fi

read -p "Git Commit and Sync? " user_input

if [[ $user_input =~ ^[Yy]$ ]]; then
    currentDate=$(date +"SYS: %Y-%m-%d %H:%M:%S")
    git commit -m "$currentDate" &> git-commit.log
    git push origin main &> git-sync.log
    if [ $? -eq 1 ]; then
        echo "Git failed to Commit and Sync."
        echo "Please check git-commit.log git-sync.log for more details"
        exit 1
    else
        echo "Git Commit and Sync Successfully!"
    fi
elif [[ $user_input =~ ^[Nn]$ ]]; then
    echo "Configuration not backed up."
fi

# 1. Enable sudo 
# 3. Early exit if not git change is detected
# 4. Auto format all nix code 
# 5. Output Rebuilding NixOS... (preferably with a loading)
# 6. Run the rebuild command with stripped error message
# 7. Output the Rebuild error and the error message if detected (ask the user to check the log file)
# 8. git commit with the time and date if successful build
# 9. Output rebuild successfully!!!

# https://gist.github.com/0atman/1a5133b842f929ba4c1e195ee67599d5
