#!/usr/bin/env bash

source assets/bla/bla.sh
trap BLA::stop_loading_animation SIGINT

sudo git add .

BLA::start_loading_animation "${BLA_passing_dots[@]}"
    sudo nixos-rebuild switch --flake ~/nixos --impure 
        &> nixos-switch.log || 
        (cat nixos-switch.log | grep --color error && 
        exit 1)
BLA::stop_loading_animation

notify-send "NixOS finished rebuilding!"
echo "NixOS finished rebuilding!"

sudo chown -R udontur:777 ./.git
currentDate=$(date +"SYS: %Y-%m-%d %H:%M:%S")
git commit -m "$currentDate" 
    &> git-commit.log

read -p "Back it up? " user_input

if [[ $user_input =~ ^[Yy]$ ]]; then
    git push origin main 
        &> git-sync.log || 
        (git push origin main && 
        exit 1)
    if [ $? -ne 0 ]; then
        echo "Configuration FAILED to back up :c"
        exit 1
    else
        echo "Configuration backed up :D"
    fi
else
    echo "Configuration NOT backed up :c"
fi