#!/usr/bin/env bash

sudo echo "NixOS Rebuilding... "

sudo git add .

# Rebuild, output simplified errors, log trackebacks
sudo nixos-rebuild switch --flake ~/nixos-laptop --impure &> nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)

if [ $? -eq 1 ]; then
    echo "NixOS Failed to Rebuild."
    echo "Please check nixos-switch.log and the error message"
    exit 1
fi

echo "NixOS Rebuilt Successfully!" 

read -p "Git Commit and Sync? " user_input

currentDate=$(date +"SYS: %Y-%m-%d %H:%M:%S")

if [[ $user_input =~ ^[Yy]$ ]]; then
    git commit -m "$currentDate"
    git push origin main
elif [[ $user_input =~ ^[Nn]$ ]]; then
    echo "Configuration NOT backedup"
fi

# 1. Enable sudo 
# 3. Early exit if not git change is detected
# 4. Auto format all nix code 
# 5. Output Rebuilding NixOS... (preferably with a loading)
# 6. Run the rebuild command with stripped error message
# 7. Output the Rebuild error and the error message if detected (ask the user to check the log file)
# 8. git commit with the time and date if successful build
# 9. Output rebuild successfully!!!

# https://gist.github.com/0atman/1a5133b842f929ba4c1e195ee67599d5
